# Generated by Django 5.0.2 on 2024-03-15 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_level', models.CharField(choices=[('Highschool', 'Highschool'), ('Undergraduate', 'Undergraduate'), ('Masters', 'Masters'), ('Doctoral', 'Doctoral'), ('TEAS 7', 'TEAS 7'), ('HESI', 'HESI')], default='Highschool', max_length=20)),
                ('type_of_service', models.CharField(choices=[('Writing from scratch', 'Writing from scratch'), ('Editing', 'Editing'), ('Problem solving', 'Problem solving'), ('Paraphrasing/Rewriting', 'Paraphrasing/Rewriting'), ('TEAS 7', 'TEAS 7'), ('HESI', 'HESI')], default='Writing from scratch', max_length=30)),
                ('type_of_paper', models.CharField(choices=[('Essay', 'Essay'), ('Article', 'Article'), ('Assignment', 'Assignment'), ('Content', 'Content'), ('Business plan', 'Business plan'), ('Movie Review', 'Movie Review')], default='Essay', max_length=20)),
                ('subject_area', models.CharField(choices=[('Any', 'Select Subject'), ('Archaeology', 'Archaeology'), ('Architecture', 'Architecture'), ('Arts', 'Arts'), ('Astronomy', 'Astronomy'), ('Biology', 'Biology'), ('Business', 'Business'), ('Chemistry', 'Chemistry'), ('Childcare', 'Childcare'), ('Computers', 'Computers'), ('Counseling', 'Counseling'), ('Criminology', 'Criminology'), ('Economics', 'Economics'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Environmental-Studies', 'Environmental-Studies'), ('Ethics', 'Ethics'), ('Ethnic-Studies', 'Ethnic-Studies'), ('Finance', 'Finance'), ('Food-Nutrition', 'Food-Nutrition'), ('Geography', 'Geography'), ('Healthcare', 'Healthcare'), ('HESI Test', 'HESI Test'), ('History', 'History'), ('Law', 'Law'), ('Linguistics', 'Linguistics'), ('Literature', 'Literature'), ('Management', 'Management'), ('Mathematics', 'Mathematics'), ('Medicine', 'Medicine'), ('Music', 'Music'), ('NACE', 'NACE'), ('NCLEX-RN', 'NCLEX-RN'), ('Nursing', 'Nursing'), ('Philosophy', 'Philosophy'), ('Physical-Education', 'Physical-Education'), ('Physics', 'Physics'), ('Political-Science', 'Political-Science'), ('Programming', 'Programming'), ('Psychology', 'Psychology'), ('Religion', 'Religion'), ('Sociology', 'Sociology'), ('Statistics', 'Statistics'), ('TEAS 7 Test', 'TEAS 7 Test')], default='Any', max_length=50)),
                ('title', models.CharField(max_length=20)),
                ('paper_instructions', models.CharField(max_length=200)),
                ('additional_material', models.FileField(upload_to='images/%Y/%m/%d/')),
                ('paper_format', models.CharField(max_length=20)),
                ('number_of_pages', models.CharField(choices=[('Double Spaced', 'Double Spaced'), ('Single Spaced', 'Single Spaced')], default='Double Spaced', max_length=20)),
                ('number_of_pages_increment', models.IntegerField(default=1)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='USD', max_length=20)),
                ('sources', models.IntegerField(default=1)),
                ('powerpoint_slides', models.IntegerField(default=0)),
                ('deadline', models.CharField(choices=[('6hrs', '6hrs'), ('12hrs', '12hrs'), ('24hrs', '24hrs'), ('48hrs', '48hrs'), ('5days', '5days'), ('10days', '10days'), ('14days', '14days'), ('30days', '30days')], default='6hrs', max_length=20)),
                ('writer_category', models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium'), ('Platinum', 'Platinum')], default='Standard', max_length=20)),
                ('preferred_writers_id', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('email', models.EmailField(max_length=254)),
                ('postal_code', models.IntegerField()),
                ('address', models.CharField(max_length=191)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
            ],
        ),
    ]
