# Generated by Django 4.2.13 on 2024-06-20 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_material',
        ),
        migrations.CreateModel(
            name='AdditionalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_materials', to='app1.order')),
            ],
        ),
    ]
