# Generated by Django 5.0.2 on 2024-03-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_coupon_alter_customer_academic_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='additional_material',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_writers_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
