# Generated by Django 4.2.13 on 2024-06-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_order_additional_material_additionalmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_material',
            field=models.FileField(default='uploads/default_file.txt', upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='AdditionalMaterial',
        ),
    ]
