# Generated by Django 3.2.9 on 2024-05-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_customer_additional_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='additional_material',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
    ]
