# Generated by Django 4.2.13 on 2024-06-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_order_additional_material_delete_additionalmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_material',
        ),
    ]
