# Generated by Django 3.2.9 on 2024-05-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='name',
            field=models.CharField(default='empty', max_length=255),
        ),
    ]
