# Generated by Django 3.2.9 on 2024-05-23 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_referral_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(default='No Content'),
        ),
        migrations.AddField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='No Subject', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default='No Content'),
        ),
    ]
