# Generated by Django 3.2.9 on 2024-06-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('In Progress', 'In Progress'), ('cancelled', 'Cancelled'), ('cancelled', 'Cancelled'), ('approved', 'Approved'), ('revision', 'Revision'), ('completed', 'Completed'), ('editing', 'Editing'), ('in_progress', 'In Progress')], default='pending', max_length=50),
        ),
    ]
