# Generated by Django 3.2.9 on 2024-06-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='order',
            name='academic_level',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='additional_material',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_pages',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_pages_increment',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='paper_format',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='paper_instructions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='powerpoint_slides',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_writers_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sources',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='subject_area',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='type_of_service',
            field=models.CharField(default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='writer_category',
            field=models.CharField(default='Standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='Unknown', max_length=191),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('approved', 'Approved'), ('revision', 'Revision'), ('editing', 'Editing')], default='pending', max_length=50),
        ),
    ]
