name: Deploy to cpanel via SFTP

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Deploy to cpanel via SFTP
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: nurseprofessors.com
                  username: ${{ secrets.sftp_USERNAME }} # Use the correct secret for SFTP username
                  password: ${{ secrets.sftp_PASSWORD }} # Use the correct secret for SFTP password
                  server-dir: ./PetersNurseprofessorsProject/ # Path to the directory containing the code to be uploaded.
                  exclude: ".git/ .github/" # You can specify files/directories to exclude.
                  protocol: sftp # Specify SFTP as the protocol
