name: Deploy to cPanel via FTP

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ matrix.python-version }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv ./venv
          source ./venv/bin/activate
          pip install -r requirements.txt

      - name: Collect static files
        run: |
          source ./venv/bin/activate
          python manage.py collectstatic --noinput

      - name: List files for debugging
        run: |
          echo "Listing all files before deployment:"
          find . -type f | sort

      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: nurseprofessors.com
          username: ${{ secrets.ftp_USERNAME }}
          password: ${{ secrets.ftp_PASSWORD }}
          server-dir: ./PetersNurseprofessorsProject/
          exclude: |
            .git/
            .git/**
            .github/
            .github/**
            venv/
            venv/**
            __pycache__/
            __pycache__/**
            *.pyc
            *.pyo
            .DS_Store
            node_modules/
            node_modules/**
            .ftp-deploy-sync-state.json
            .env
            .venv
            *.log
            logs/
            logs/**
            *.tmp
            *.bak
            *.md
            tests/
            tests/**
            docs/
            docs/**
            .idea/
            .idea/**
            .vscode/
            .vscode/**
            .pytest_cache/
            .pytest_cache/**
            *.test.js
            *.spec.js
            *.config.js
            .eslintignore
            .eslintrc.js
            .babelrc
            .editorconfig
            .gitignore

      - name: Trigger migration script
        run: |
          echo "Triggering migration script..."
          curl -v -X GET "https://nurseprofessors.com/run-migrations/?secret=${{ secrets.MIGRATION_SECRET }}"
